// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/axxapy/fleetlock-consul/internal/storage (interfaces: ConsulKVClient,ConsulSessionClient)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_consul.go -package=mocks github.com/axxapy/fleetlock-consul/internal/storage ConsulKVClient,ConsulSessionClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	api "github.com/hashicorp/consul/api"
	gomock "go.uber.org/mock/gomock"
)

// MockConsulKVClient is a mock of ConsulKVClient interface.
type MockConsulKVClient struct {
	ctrl     *gomock.Controller
	recorder *MockConsulKVClientMockRecorder
	isgomock struct{}
}

// MockConsulKVClientMockRecorder is the mock recorder for MockConsulKVClient.
type MockConsulKVClientMockRecorder struct {
	mock *MockConsulKVClient
}

// NewMockConsulKVClient creates a new mock instance.
func NewMockConsulKVClient(ctrl *gomock.Controller) *MockConsulKVClient {
	mock := &MockConsulKVClient{ctrl: ctrl}
	mock.recorder = &MockConsulKVClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsulKVClient) EXPECT() *MockConsulKVClientMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockConsulKVClient) Acquire(p *api.KVPair, q *api.WriteOptions) (bool, *api.WriteMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", p, q)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*api.WriteMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Acquire indicates an expected call of Acquire.
func (mr *MockConsulKVClientMockRecorder) Acquire(p, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockConsulKVClient)(nil).Acquire), p, q)
}

// Delete mocks base method.
func (m *MockConsulKVClient) Delete(key string, w *api.WriteOptions) (*api.WriteMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key, w)
	ret0, _ := ret[0].(*api.WriteMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockConsulKVClientMockRecorder) Delete(key, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConsulKVClient)(nil).Delete), key, w)
}

// Get mocks base method.
func (m *MockConsulKVClient) Get(key string, q *api.QueryOptions) (*api.KVPair, *api.QueryMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key, q)
	ret0, _ := ret[0].(*api.KVPair)
	ret1, _ := ret[1].(*api.QueryMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockConsulKVClientMockRecorder) Get(key, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConsulKVClient)(nil).Get), key, q)
}

// Put mocks base method.
func (m *MockConsulKVClient) Put(p *api.KVPair, q *api.WriteOptions) (*api.WriteMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", p, q)
	ret0, _ := ret[0].(*api.WriteMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockConsulKVClientMockRecorder) Put(p, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockConsulKVClient)(nil).Put), p, q)
}

// MockConsulSessionClient is a mock of ConsulSessionClient interface.
type MockConsulSessionClient struct {
	ctrl     *gomock.Controller
	recorder *MockConsulSessionClientMockRecorder
	isgomock struct{}
}

// MockConsulSessionClientMockRecorder is the mock recorder for MockConsulSessionClient.
type MockConsulSessionClientMockRecorder struct {
	mock *MockConsulSessionClient
}

// NewMockConsulSessionClient creates a new mock instance.
func NewMockConsulSessionClient(ctrl *gomock.Controller) *MockConsulSessionClient {
	mock := &MockConsulSessionClient{ctrl: ctrl}
	mock.recorder = &MockConsulSessionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsulSessionClient) EXPECT() *MockConsulSessionClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConsulSessionClient) Create(se *api.SessionEntry, q *api.WriteOptions) (string, *api.WriteMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", se, q)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*api.WriteMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockConsulSessionClientMockRecorder) Create(se, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConsulSessionClient)(nil).Create), se, q)
}

// Destroy mocks base method.
func (m *MockConsulSessionClient) Destroy(id string, q *api.WriteOptions) (*api.WriteMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Destroy", id, q)
	ret0, _ := ret[0].(*api.WriteMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Destroy indicates an expected call of Destroy.
func (mr *MockConsulSessionClientMockRecorder) Destroy(id, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Destroy", reflect.TypeOf((*MockConsulSessionClient)(nil).Destroy), id, q)
}
